services:
  nginx:
    build: requirements/nginx/.
    image: nginx:42
    env_file: 
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: requirements/wordpress/.
    image: wordpress:42
    env_file: 
      - .env   
    expose:
      - "9000"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build: requirements/mariadb/.
    image: mariadb:42
    env_file: 
      - .env 
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge
  
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: '/home/pbengoec/data/wordpress'
      o: 'bind'
      type: 'none'
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: '/home/pbengoec/data/mariadb'
      o: 'bind'
      type: 'none'
